dist: xenial # ubuntu 16.04
language: python
python:
  - '3.7.7'
cache:
  - pip

install:
  - sudo apt-get install -y libsndfile-dev ffmpeg
  - cat requirements.txt | grep -v -E "warp_rnnt|horovod|kenlm"  > requirements_cpu.txt && pip install -r requirements_cpu.txt
  - pip install numba==0.48 && pip freeze

script:
  - cd tests && pytest && bash check_cmds.sh

notifications:
  email: false

branches:
  only:
    - master
