dist: xenial # ubuntu 16.04
language: python
python: 
  - '3.7.7'

install:
  - python -m pip install --upgrade
  - cat requirements.txt | grep -v -E "warp_rnnt|horovod|kenlm"  > requirements_cpu.txt && pip install -r requirements_cpu.txt

scripts:
  - cd tests && pytest