nnet: "att"

nnet_conf:
  input_size: 80
  enc_type: "concat"
  enc_proj: 512
  enc_kwargs:
    conv1d:
      out_features: 512
      dim: 512
      num_layers: 3
      stride: [2, 2, 2]
      dilation: [1, 1, 2]
    pytorch_rnn:
      rnn: "lstm"
      num_layers: 3
      bidirectional: true
      dropout: 0.2
      hidden: 320
  dec_dim: 512
  dec_kwargs:
    dec_rnn: "lstm"
    dropout_on: "input"
    rnn_layers: 2
    rnn_hidden: 512  # must eq decoder_dim
    rnn_dropout: 0.2
    emb_dropout: 0.3
    input_feeding: true
    vocab_embeded: true
  att_type: "ctx"
  att_kwargs:
    att_dim: 512

task: "ctc_xent"

task_conf:
  lsm_factor: 0.1
  ctc_weight: 0.2

asr_transform:
  feats: "fbank-log-cmvn-aug"
  frame_len: 400
  frame_hop: 160
  window: "hamm"
  round_pow_of_two: true
  sr: 16000
  num_mels: 80
  norm_mean: true
  norm_var: true
  aug_prob: 0.5
  aug_mask_zero: false
  aug_max_frame: 80
  num_aug_bands: 1
  num_aug_frame: 1

trainer_conf:
  optimizer: "adam"
  optimizer_kwargs:
    lr: 1.0e-3
    weight_decay: 1.0e-5
  lr_scheduler: "exp_lr"
  lr_scheduler_period: "step"
  lr_scheduler_kwargs:
    time_stamps: [800, 40000, 100000]
    peak_lr: 1.0e-3
    stop_lr: 1.0e-5
  ss_scheduler: "linear"
  ss_scheduler_kwargs:
    ssr: 0.2
    epoch_beg: 10
    epoch_end: 26
    update_interval: 4
  no_impr: 6
  no_impr_thres: 0.2
  clip_gradient: 5
  report_metrics: ["loss", "accu", "@ctc"]
  stop_criterion: "accu"

data_conf:
  fmt: "am_raw"
  loader:
    max_token_num: 400
    adapt_token_num: 150
    max_dur: 30 # (s)
    min_dur: 0.4 # (s)
    adapt_dur: 10 # (s)
  train:
    wav_scp: "data/aishell_v1/train/wav.scp"
    utt2dur: "data/aishell_v1/train/utt2dur"
    text: "data/aishell_v1/train/text"
  valid:
    wav_scp: "data/aishell_v1/dev/wav.scp"
    utt2dur: "data/aishell_v1/dev/utt2dur"
    text: "data/aishell_v1/dev/text"
