nnet: "rnn_lm"

nnet_conf:
  embed_size: 2048
  tie_weights: true
  rnn: lstm
  dropout: 0.2
  num_layers: 3
  hidden_size: 2048

task: "lm"

trainer_conf:
  optimizer: "adam"
  optimizer_kwargs:
    lr: 1.0e-3
    weight_decay: 1.0e-5
  lr_scheduler_kwargs:
    min_lr: 1.0e-8
    patience: 1
    factor: 0.5
  no_impr: 8
  no_impr_thres: 0
  clip_gradient: 10
  report_metrics: ["loss", "accu", "@ppl"]
  stop_criterion: "loss"

data_conf:
  fmt: "lm_utt"
  loader:
    min_token_num: 10
    max_token_num: 300
    min_batch_size: 4
    adapt_token_num: 50
    chunk_size_for_sort: 48000
  train:
    text: "data/librispeech/lm/train.token"
  valid:
    text: "data/librispeech/lm/dev.token"
