nnet: crn

task: spectra_appro
task_conf:
  num_spks: 1
  permute: false
  truncated: 1
  phase_sensitive: true
  masking: true

nnet_conf:
  output_nonlinear: "sigmoid"
  causal_conv: true

enh_transform:
  feats: "spectrogram-log-cmvn"
  frame_len: 320
  frame_hop: 100
  window: "sqrthann"
  round_pow_of_two: false

data_conf:
  fmt: "enh"
  loader:
    sr: 16000
    chunk_size: 64000
  train:
    mix_scp: "data/enh/train/noisy.scp"
    ref_scp: "data/enh/train/clean.scp"
  valid:
    mix_scp: "data/enh/dev/noisy.scp"
    ref_scp: "data/enh/dev/clean.scp"

trainer_conf:
  optimizer: "adam"
  optimizer_kwargs:
    lr: 1.0e-3
    weight_decay: 1.0e-5
  lr_scheduler_kwargs:
    min_lr: 1.0e-8
    patience: 1
    factor: 0.5
  no_impr: 4
  no_impr_thres: 0.2
  stop_criterion: "loss"
  clip_gradient: 5