task: sisnr

task_conf:
  num_spks: 1
  permute: false

nnet: dcunet

nnet_conf:
  cplx: true
  num_layers: 16
  causal_conv: false

enh_transform:
  feats: "spectrogram-log-cmvn"
  frame_len: 1024
  frame_hop: 256
  window: "sqrthann"
  round_pow_of_two: true

data_conf:
  fmt: "enh"
  loader:
    sr: 16000
    chunk_size: 32000
  train:
    mix_scp: "data/enh/train/noisy.scp"
    ref_scp: "data/enh/train/clean.scp"
  valid:
    mix_scp: "data/enh/dev/noisy.scp"
    ref_scp: "data/enh/dev/clean.scp"

trainer_conf:
  optimizer: "adam"
  optimizer_kwargs:
    lr: 1.0e-3
    weight_decay: 1.0e-5
  lr_scheduler_kwargs:
    min_lr: 1.0e-8
    patience: 1
    factor: 0.5
  no_impr: 4
  no_impr_thres: 0.2
  stop_criterion: "loss"
  clip_gradient: 5