# 8 GPU, DDP, 256 batch size
# WER (%) Report:
# Total (2620 utterances): 2356/52576 = 4.48%, SUB/INS/DEL = 1899/158/299
# WER (%) Report:
# Total (2939 utterances): 6035/52343 = 11.53%, SUB/INS/DEL = 4834/432/769

nnet: "att"

nnet_conf:
  input_size: 80
  enc_type: "concat"
  enc_proj: 1024
  enc_kwargs:
    conv2d:
      out_features: -1
      channel: 32
      num_layers: 2
      stride: 2
      padding: 1
      kernel_size: 3
    pytorch_rnn:
      bidirectional: true
      dropout: 0.3
      hidden: 1024
      num_layers: 4
  dec_dim: 1024
  dec_kwargs:
    dec_rnn: "lstm"
    rnn_layers: 2
    rnn_hidden: 1024
    rnn_dropout: 0.2
    emb_dropout: 0.2
    dropout: 0.2
    input_feeding: true
    vocab_embeded: true
  att_type: "ctx"
  att_kwargs:
    att_dim: 1024

task: "ctc_xent"

task_conf:
  ctc_weight: 0.2
  label_count: data/librispeech/16k.train.label_count
  lsm_factor: 0.1
  lsm_method: unigram

asr_transform:
  feats: "perturb-emph-fbank-log-aug"
  frame_len: 400
  frame_hop: 160
  window: "hamm"
  round_pow_of_two: true
  use_power: true
  pre_emphasis: 0.97
  sr: 16000
  num_mels: 80
  min_freq: 20
  norm_mean: true
  norm_var: true
  norm_per_band: false
  aug_prob: 1
  aug_max_bands: 27
  aug_max_frame: 100
  aug_mask_zero: true
  num_aug_bands: 2
  num_aug_frame: 2

trainer_conf:
  optimizer: "adam"
  optimizer_kwargs:
    lr: 1.0e-3
    weight_decay: 1.0e-5
  lr_scheduler: "warmup_exp_decay_lr"
  lr_scheduler_period: "step"
  lr_scheduler_kwargs:
    time_stamps: [500, 40000, 160000]
    peak_lr: 1.0e-3
    stop_lr: 1.0e-5
  no_impr: 6
  no_impr_thres: 0.1
  clip_gradient: 1
  report_metrics: ["loss", "accu", "@ctc"]
  stop_criterion: "accu"

data_conf:
  fmt: "am_raw"
  loader:
    max_token_num: 400
    adapt_token_num: 150
    max_dur: 30 # (s)
    min_dur: 0.4 # (s)
    adapt_dur: 10 # (s)
  train:
    text: data/librispeech/train/token
    utt2dur: data/librispeech/train/utt2dur
    wav_scp: data/librispeech/train/wav.scp
  valid:
    text: data/librispeech/dev/token
    utt2dur: data/librispeech/dev/utt2dur
    wav_scp: data/librispeech/dev/wav.scp
