# duplicated, we use github workflow now

dist: xenial # ubuntu 16.04
language: python
python:
  - '3.7.7'
cache:
  - pip

install:
  - bash .ci/install_test_deps.sh

script:
  - cd tests && pytest && bash check_cmds.sh

notifications:
  email: false

branches:
  only:
    - master
