nnet: "att"

nnet_conf:
  input_size: 240
  encoder_type: "custom_rnn"
  encoder_proj: 512
  encoder_kwargs:
    rnn: "lstm"
    rnn_layers: 4
    rnn_bidir: true
    rnn_dropout: 0.2
    rnn_hidden: 320
    rnn_project: 512
    layernorm: true
  decoder_dim: 256
  decoder_kwargs:
    dec_rnn: "lstm"
    rnn_layers: 2
    rnn_hidden: 256  # must eq decoder_dim
    rnn_dropout: 0.3
    input_feeding: true
    vocab_embeded: true
  att_type: "loc"
  att_kwargs:
    att_dim: 256
    att_channels: 128
    att_kernel: 11

task: "ctc_xent"

task_conf:
  lsm_factor: 0
  ctc_weight: 0.2

asr_transform:
  feats: "fbank-log-cmvn-splice"
  frame_len: 400
  frame_hop: 160
  window: "hamm"
  round_pow_of_two: true
  sr: 16000
  num_mels: 80
  lctx: 1
  rctx: 1

trainer_conf:
  optimizer: "adam"
  optimizer_kwargs:
    lr: 1.0e-3
    weight_decay: 1.0e-5
  lr_scheduler_kwargs:
    min_lr: 1.0e-8
    patience: 1
    factor: 0.5
  no_impr: 6
  no_impr_thres: 0.1
  clip_gradient: 0.25
  stop_criterion: "accu"

data_conf:
  fmt: "am_wav"
  loader:
    max_token_num: 400
    adapt_token_num: 150
    max_dur: 30 # (s)
    min_dur: 0.4 # (s)
    adapt_dur: 10 # (s)
  train:
    wav_scp: "data/timit/train/wav.scp"
    utt2dur: "data/timit/train/utt2dur"
    token: "data/timit/train/token"
  valid:
    wav_scp: "data/timit/dev/wav.scp"
    utt2dur: "data/timit/dev/utt2dur"
    token: "data/timit/dev/token"
