nnet: "transducer"

nnet_conf:
  input_size: 240
  enc_type: "variant_rnn"
  enc_proj: 512
  enc_kwargs:
    rnn: "lstm"
    num_layers: 4
    bidirectional: true
    dropout: 0.2
    hidden: 512
    project: 512
    layernorm: true
  dec_kwargs:
    embed_size: 512
    jot_dim: 512
    dec_rnn: "lstm"
    dec_layers: 3
    dec_hidden: 512
    dec_dropout: 0.2

task: "transducer"

asr_transform:
  feats: "fbank-log-cmvn-splice"
  frame_len: 400
  frame_hop: 160
  window: "hamm"
  round_pow_of_two: true
  sr: 16000
  num_mels: 80
  lctx: 1
  rctx: 1

trainer_conf:
  optimizer: "adam"
  optimizer_kwargs:
    lr: 1.0e-4
    weight_decay: 1.0e-5
  lr_scheduler_kwargs:
    min_lr: 1.0e-8
    patience: 1
    factor: 0.5
  no_impr: 6
  no_impr_thres: 0.1
  clip_gradient: 0.25
  report_metrics: ["loss"]
  stop_criterion: "loss"

data_conf:
  fmt: "am_raw"
  loader:
    max_token_num: 400
    adapt_token_num: 150
    max_dur: 30 # (s)
    min_dur: 0.4 # (s)
    adapt_dur: 10 # (s)
  train:
    wav_scp: "data/timit/train/wav.scp"
    utt2dur: "data/timit/train/utt2dur"
    text: "data/timit/train/text"
  valid:
    wav_scp: "data/timit/dev/wav.scp"
    utt2dur: "data/timit/dev/utt2dur"
    text: "data/timit/dev/text"
