# common encoder-decoder structure with enhancement front-end

nnet: "beam_att"

nnet_conf:
  asr_input_size: 640
  mode: "ti"
  fe_conf:
    num_bins: 257
    num_channels: 4
    spatial_filters: 8
    spectra_filters: 80
  # back-end
  encoder_type: "fsmn"
  encoder_proj: 512
  encoder_kwargs:
    tdnn_dim: 512
    tdnn_layers: 3
    tdnn_stride: "2,2,2"
    tdnn_dilation: "1,1,2"
    fsmn_layers: 4
    fsmn_lctx: 10
    fsmn_rctx: 10
    fsmn_norm: "LN"
    fsmn_project: 256
  decoder_dim: 512
  decoder_kwargs:
    dec_rnn: "lstm"
    rnn_layers: 2
    rnn_hidden: 512  # must eq decoder_dim
    rnn_dropout: 0
    input_feeding: True
    vocab_embeded: True
  att_type: "ctx"
  att_kwargs:
    att_dim: 512

task: "ctc_xent"

task_conf:
  lsm_factor: 0.1
  ctc_regularization: 0.2

enh_transform:
  feats: ""
  aug_prob: 0.5
  aug_max_bands: 90
  aug_max_frame: 40
  num_aug_bands: 2
  num_aug_frame: 2
  frame_len: 512
  frame_hop: 160
  window: "hann"

trainer_conf:
  optimizer: "adam"
  optimizer_kwargs:
    lr: 1.0e-3
    weight_decay: 1.0e-5
  lr_scheduler_kwargs:
    min_lr: 1.0e-8
    patience: 1
    factor: 0.5
  ss_scheduler: "linear"
  ss_scheduler_kwargs:
    ssr: 0.3
    epoch_beg: 10
    epoch_end: 28
    update_interval: 3
  no_impr: 4
  no_impr_thres: 0.2
  clip_gradient: 5
  stop_criterion: "accu"

data_conf:
  fmt: "wav"  # or "kaldi"
  loader:
    max_token_num: 400
    adapt_token_num: 150
    max_dur: 30 # (s)
    min_dur: 0.4 # (s)
    adapt_dur: 8 # (s)
  train:
    wav_scp: "data/far_simu_iso_asv2/train/wav.scp"
    utt2dur: "data/far_simu_iso_asv2/train/utt2dur"
    token: "data/far_simu_iso_asv2/train/token"
  valid:
    wav_scp: "data/far_simu_iso_asv2/dev/wav.scp"
    utt2dur: "data/far_simu_iso_asv2/dev/utt2dur"
    token: "data/far_simu_iso_asv2/dev/token"