# transformer-based encoder-decoder structure with joint-mvdr front-end

nnet_type: mvdr_transformer

enh_transform:
  feats: "spectrogram-log-cmvn-ipd"
  frame_len: 400
  frame_hop: 160
  window: "hann"
  norm_mean: True
  norm_var: True
  ipd_index: "1,0;2,0;3,0"
  cos_ipd: True

asr_transform:
  feats: "abs-mel-log-cmvn"
  sr: 16000
  num_mels: 80
  norm_mean: True
  norm_var: True

nnet_conf:
  asr_input_size: 80
  # front-end
  enh_input_size: 1028
  num_bins: 257
  mvdr_kwargs:
    mask_norm: True
    eps: 1.0e-5
    att_dim: 512
  mask_net_kwargs:
    rnn: "lstm"
    rnn_layers: 3
    rnn_hidden: 320
    rnn_dropout: 0.2
    rnn_bidir: True
    output_act: "sigmoid"
  encoder_type: "transformer"
  encoder_kwargs:
    att_dim: 256
    att_dropout: 0.2
    nhead: 4
    input_embed: conv2d
    pos_dropout: 0.2
    num_layers: 6
    feedforward_dim: 512
  decoder_kwargs:
    att_dim: 256
    att_dropout: 0.2
    nhead: 4
    pos_dropout: 0.2
    num_layers: 6
    feedforward_dim: 512

task: "ctc_xent"

task_conf:
  lsm_factor: 0.1
  ctc_regularization: 0.2

trainer_conf:
  clip_gradient: 5
  lr_scheduler_kwargs:
    factor: 0.5
    min_lr: 1.0e-08
    patience: 1
  no_impr: 6
  no_impr_thres: 0.2
  optimizer: adam
  optimizer_kwargs:
    lr: 0.0001
    weight_decay: 1.0e-05
  stop_criterion: accu

data_conf:
  fmt: wav
  loader:
    adapt_dur: 10
    adapt_token_num: 150
    channel: -1
    max_dur: 30
    max_token_num: 400
    min_dur: 0.4
  train:
    token: data/far_simu_iso_asv2/train/token
    utt2dur: data/far_simu_iso_asv2/train/utt2dur
    wav_scp: data/far_simu_iso_asv2/train/wav.scp
  valid:
    token: data/far_simu_iso_asv2/dev/token
    utt2dur: data/far_simu_iso_asv2/dev/utt2dur
    wav_scp: data/far_simu_iso_asv2/dev/wav.scp