# default conf

nnet_conf:
  # attention
  att_type: "ctx"
  att_kwargs:
    att_dim: 512
  input_size: 240
  # encoder
  encoder_type: "layernorm"
  encoder_dim: 256
  encoder_proj: 512
  encoder_layers: 3
  encoder_rnn: "lstm"
  encoder_dropout: 0.2
  # decoder
  decoder_dim: 512
  decoder_layers: 1
  decoder_dropout: 0
  decoder_rnn: "lstm"

trainer_conf:
  optimizer: "adam"
  optimizer_kwargs:
    lr: 1.0e-3
    weight_decay: 1.0e-5
  lr_scheduler_kwargs:
    min_lr: 1.0e-8
    patience: 1
    factor: 0.5
  logging_period: 200
  gradient_clip: 10
  no_impr: 6
  label_smooth: 0
  schedule_sampling: 0

data_conf:
  loader:
    max_token_num: 400
    max_frame_num: 3000 # 30s
    min_frame_num: 40   # 0.4s
    adapt_frame_num: 800  # 8s
    adapt_token_num: 150
  train:
    token_scp: "data/train/token.scp"
    feats_scp: "data/train/feats.scp"
    utt2num_frames: "data/train/utt2num_frames"
  valid:
    token_scp: "data/valid/token.scp"
    feats_scp: "data/valid/feats.scp"
    utt2num_frames: "data/valid/utt2num_frames"