# CER: 9.50 on aishell_v1 test set

nnet_type: "las"

nnet_conf:
  input_size: 240
  encoder_type: "pyramid"
  encoder_proj: 256
  encoder_kwargs: 
    hidden_size: 256
    num_layers: 3
    dropout: 0.2
    pyramid: True
    ln: False
    bidirectional: True
    add_forward_backward: False
  decoder_dim: 256
  decoder_kwargs:
    rnn: "lstm"
    num_layers: 2
    hidden_size: 256  # must eq decoder_dim
    dropout: 0
    input_feeding: True
  att_type: "dot"
  att_kwargs:
    att_dim: 512

asr_transform:
  feats: "fbank-log-cmvn-aug-delta"
  frame_len: 400
  frame_hop: 160
  window: "hamm"
  round_pow_of_two: True
  sr: 16000
  num_mels: 80
  norm_mean: True
  norm_var: True
  ctx: 2
  order: 2
  aug_prob: 0.8
  wrap_step: 4

trainer_conf:
  optimizer: "adam"
  optimizer_kwargs:
    lr: 1.0e-3
    weight_decay: 1.0e-5
  lr_scheduler_kwargs:
    min_lr: 1.0e-8
    patience: 1
    factor: 0.5
  logging_period: 100
  gradient_clip: 5
  no_impr: 4
  lsm_factor: 0.1
  schedule_sampling: 0.2

data_conf:
  fmt: "wav"  # or "kaldi"
  loader:
    max_token_num: 400
    adapt_token_num: 150
    max_dur: 30 # (s)
    min_dur: 0.4 # (s)
    adapt_dur: 8 # (s)
  train:
    wav_scp: "data/aishell_v1/train/wav.scp"
    utt2dur: "data/aishell_v1/train/utt2dur"
    token: "data/aishell_v1/train/token"
  valid:
    wav_scp: "data/aishell_v1/dev/wav.scp"
    utt2dur: "data/aishell_v1/dev/utt2dur"
    token: "data/aishell_v1/dev/token"