# default conf

nnet_type: "transformer"

nnet_conf:
  input_dim: 80
  input_embed: "conv2d"
  att_dim: 256
  nhead: 4
  feedforward_dim: 512
  pos_dropout: 0.1
  att_dropout: 0.2
  num_layers: 6

asr_transform:
  feats: "fbank-log-cmvn-aug"
  frame_len: 400
  frame_hop: 160
  window: "hamm"
  round_pow_of_two: True
  sr: 16000
  num_mels: 80
  norm_mean: True
  norm_var: True
  aug_prob: 0.5

trainer_conf:
  optimizer: "adam"
  optimizer_kwargs:
    lr: 1.0e-4
    weight_decay: 1.0e-5
  lr_scheduler_kwargs:
    min_lr: 1.0e-8
    patience: 1
    factor: 0.5
  no_impr: 6
  no_impr_thres: 0.002
  lsm_factor: 0.1
  clip_gradient: 5
  ctc_regularization: 0.2
  stop_criterion: "accu"

data_conf:
  fmt: "wav"  # or "kaldi"
  loader:
    max_token_num: 400
    adapt_token_num: 150
    max_dur: 30 # (s)
    min_dur: 0.4 # (s)
    adapt_dur: 10 # (s)
    channel: 0
  train:
    wav_scp: "data/far_simu_iso_asv2/train/wav.scp"
    utt2dur: "data/far_simu_iso_asv2/train/utt2dur"
    token: "data/far_simu_iso_asv2/train/token"
  valid:
    wav_scp: "data/far_simu_iso_asv2/dev/wav.scp"
    utt2dur: "data/far_simu_iso_asv2/dev/utt2dur"
    token: "data/far_simu_iso_asv2/dev/token"