name: Lint

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  flake8_check:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Flake8 check
        run: |
          pip install flake8 && flake8 --version && flake8
