name: Testing

on: [push, pull_request]


jobs:
  unit_test:
    name: Unit Testing
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          sudo apt-get install -y libsndfile-dev
          cat requirements.txt | grep -v -E "warp_rnnt|horovod|kenlm" > requirements_cpu.txt && pip install -r requirements_cpu.txt
          pip install numba==0.48
      - name: Unit Testing
        run: |
          cd tests && pytest
