name: Unit Testing

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  unit_test:
    name: Unit Testing
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]
    steps:
      - name: Set up Git LFS
        run: |
          sudo apt-get install -y curl
          curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
          sudo apt-get install git-lfs

      - name: Get aps code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          git lfs install && bash .ci/install_test_deps.sh

      - name: Run testing cases (cmd)
        run: |
          cd tests && bash check_cmds.sh

      - name: Run testing cases (lib)
        run: |
          cd tests && pytest
